server:
  port: 2100

spring:

  application:
    name: aratiri

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: invoice-listener-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

grpc:
  client:
    lnd:
      name: localhost
      port: 10009

lnd:
  path:
    tls:
      cert: ${LND_TLS_CERT_PATH}
    macaroon:
      admin: ${ADMIN_MACAROON_PATH}

jwt:
  secret: ${JWT_SECRET}
  expiration: 8400