package com.aratiri.aratiri.service.impl;

import com.aratiri.aratiri.dto.invoices.DecodedInvoicetDTO;
import com.aratiri.aratiri.dto.invoices.GenerateInvoiceDTO;
import com.aratiri.aratiri.dto.invoices.PayInvoiceDTO;
import com.aratiri.aratiri.dto.users.UserDTO;
import com.aratiri.aratiri.entity.LightningInvoiceEntity;
import com.aratiri.aratiri.exception.AratiriException;
import com.aratiri.aratiri.repository.LightningInvoiceRepository;
import com.aratiri.aratiri.service.AuthService;
import com.aratiri.aratiri.service.InvoiceService;
import com.aratiri.aratiri.utils.InvoiceUtils;
import com.google.protobuf.ByteString;
import lnrpc.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Objects;

@Service
public class InvoiceServiceImpl implements InvoiceService {

    private final Logger logger = LoggerFactory.getLogger(InvoiceServiceImpl.class);

    private final LightningInvoiceRepository lightningInvoiceRepository;
    private final AuthService authService;
    private final LightningGrpc.LightningBlockingStub lightningStub;

    public InvoiceServiceImpl(LightningGrpc.LightningBlockingStub lightningStub, LightningInvoiceRepository lightningInvoiceRepository, AuthService authService) {
        this.lightningStub = lightningStub;
        this.lightningInvoiceRepository = lightningInvoiceRepository;
        this.authService = authService;
    }

    @Override
    public GenerateInvoiceDTO generateInvoice(long satsAmount, String memo) {
        logger.info("Generating invoice for sats amount [{}] and with memo [{}]", satsAmount, memo);
        try {
            byte[] preImage = InvoiceUtils.generatePreimage();
            byte[] hash = InvoiceUtils.sha256(preImage);
            Invoice request = Invoice.newBuilder()
                    .setRHash(ByteString.copyFrom(hash))
                    .setMemo(memo)
                    .setRPreimage(ByteString.copyFrom(preImage))
                    .setValue(satsAmount).build();

            AddInvoiceResponse addInvoiceResponse = lightningStub.addInvoice(request);
            UserDTO currentUser = authService.getCurrentUser();

            long expiry = lightningStub.decodePayReq(PayReqString.newBuilder().setPayReq(addInvoiceResponse.getPaymentRequest()).build()).getExpiry();
            LightningInvoiceEntity lightningInvoice = LightningInvoiceEntity.builder()
                    .userId(currentUser.getId())
                    .amountSats(satsAmount)
                    .preimage(Base64.getEncoder().encodeToString(preImage))
                    .invoiceState(LightningInvoiceEntity.InvoiceState.OPEN)
                    .createdAt(LocalDateTime.now())
                    .expiry(expiry)
                    .paymentRequest(addInvoiceResponse.getPaymentRequest())
                    .paymentHash(addInvoiceResponse.getRHash().toStringUtf8())
                    .build();

            lightningInvoiceRepository.save(lightningInvoice);
            return new GenerateInvoiceDTO(addInvoiceResponse.getPaymentRequest());
        } catch (Exception e) {
            throw new AratiriException(e.getMessage());
        }

    }

    @Override
    public PayInvoiceDTO payInvoice(String paymentRquest) {
        return null;
    }

    @Override
    public DecodedInvoicetDTO decodePaymentRequest(String paymentRequest) {
        LightningInvoiceEntity invoice = lightningInvoiceRepository
                .findByPaymentRequest(paymentRequest)
                .orElseThrow(() -> new AratiriException("Invoice not found", HttpStatus.BAD_REQUEST));
        UserDTO userDTO = authService.getCurrentUser();

        if (!Objects.equals(invoice.getUserId(), userDTO.getId())) {
            throw new AratiriException("Lightning Invoice was not generated by the current user.", HttpStatus.BAD_REQUEST);
        }

        PayReqString payReqString = PayReqString.newBuilder().setPayReq(paymentRequest).build();
        PayReq payReq = lightningStub.decodePayReq(payReqString);

        return DecodedInvoicetDTO.builder()
                .blindedPaths(new ArrayList<>())
                .description(payReq.getDescription())
                .descriptionHash(payReq.getDescriptionHash())
                .expiry(payReq.getExpiry())
                .destination(payReq.getDestination())
                .cltvExpiry(payReq.getCltvExpiry())
                .numSatoshis(payReq.getNumSatoshis())
                .paymentAddr(Base64.getEncoder().encodeToString(payReq.getPaymentAddr().toStringUtf8().getBytes()))
                .paymentHash(payReq.getPaymentHash())
                .timestamp(Instant.ofEpochMilli(payReq.getTimestamp()).toString())
                .fallbackAddr(payReq.getFallbackAddr())
                .build();
    }

}